project: DeptEst

use_wandb: False

dataset:
  name: CustomDataset
  root: ./competition-data
  training-images: training-images
  training-depths: training-depths
  validation-images: validation-images
  validation-depths: validation-depths
  testing-images: testing-images
  img_size: 256
  batch_size: 10

model:
  name: VIT
  # filters: [1, 4, 8, 16, 32, 64]
  n_encoder_layers: 8
  d_model: 256
  nhead: 8
train:
  epochs: 10
  val_interval: 1