project: DeptEst

use_wandb: False

dataset:
  name: CustomDataset
  root: ./competition-data
  training-images: training-images
  training-depths: training-depths
  validation-images: validation-images
  validation-depths: validation-depths
  testing-images: testing-images
  img_size: 256
  batch_size: 10

model:
  name: defaultmodel

train:
  epochs: 10
  val_interval: 1